### ISSUE TITLE
[Enhancement] - Blog Page

### ISSUE THREAD

**Issue by DoozyDoz** [CirroCloudLtd/CirroCloudLtd.github.io#51]
- The Blog list has to be in linear format not grid as is now
- Provide a page to update or add blogs

**Comment by sempsmahad** [comment]
Basing on your [reply](https://github.com/CirroCloudLtd/CirroCloudLtd.github.io/pull/94#issuecomment-1484992183) i should close this and await ur changes in the new pr

**Comment by sempsmahad** [comment]
Basing on your [reply](https://github.com/CirroCloudLtd/CirroCloudLtd.github.io/pull/94#issuecomment-1484992183) i should close this and await ur changes in the new PR
